### ISSUE TITLE
Why is there a thread that is created and then immediately joined?

### ISSUE THREAD

**Issue by CrashTestCoder** [TEAM1771/2022-Code#1]
https://github.com/TEAM1771/2022-Code/blob/18f13eeaf17854266c3a96a3f1debf824942746f/src/main/cpp/Drivetrain.cpp#L232
Needlessly complicated, or misunderstood concept.

What you're doing is saying "go do this thing on another thread while I do something else" and then having the original thread sitting there twiddling its thumbs until the thread exits. You should either not join the thread at that point and let it be joined next time the function is called or make it not multithreaded. whichever is most appropriate.

**Comment by FarkasJoseph** [comment]
I left it as a thread for now, since in the future I imagine we will want the robot to be intaking & shooting balls

**Comment by FarkasJoseph** [comment]
I think it would make more sense to keep it seperate from driving, but what do you think? Should we just have a check using the timer to index and shoot where necessary in the same section of code as the driving?

**Comment by FarkasJoseph** [comment]
Actually, now that I think about it, we will most likely only be shooting while stopped, so it would make more sense to just create a separate thread for aiming and then have the trajectory following directly inside the function (not in a thread), so when the trajectory is finished, we can wait, shoot, and then start the next trajectory.

**Comment by CrashTestCoder** [comment]
I'm saying that the way this would work now is essentially not multithreaded

Side note: we should make shooting on the move a goal

**Comment by FarkasJoseph** [comment]
I understand, would you like to keep it a thread or do you think it makes more sense to just add the shooting functionality directly into the same part of the code?

**Comment by FarkasJoseph** [comment]
Is my current solution alright?
